### ISSUE TITLE
Access to Tempo Flush relais

### ISSUE THREAD

**Issue by minosrex** [hemphen/homeassistant-clevertouch#2]
I installed the integration, thank you very much for providing it!

It provides entities for the two connected radiators but not for the on/off state of the central floor heating and the boiler which are also available in the Clevertouch app. I believe the electrician used two Tempo Flush components (https://www.radson.com/nl-be/producten/zoneregeling/zoneregeling/bedieningen/bedradingscentra/touch-e3--tempco-flush) to enable this.

Is it normal that they don't show up? If yes, do you have plans to enable them?

**Comment by hemphen** [comment]
Good to hear about it being useful.

So far I have only shared what has been useful to myself. Since there is no official documented API I've only implemented support for radiators which I had access. I'd be willing to try and support other types of devices though.

I would likely need some help with data in order to figure out exactly what to display. Reading values from the appliances should be much easier. More care and more testing is also needed to support writing settings to the device.

What would be your primary use case? Monitoring or controlling?

**Comment by minosrex** [comment]
Our use case is a second home where we need to be able to turn on the relais for the floor heating beforehand, as well as make sure it's turned off when we are not there. So the TEMPCO relais is basically a connected plug with binary state on/off. 

I attach a screenshot below of how the two relais appear in the list and what is shows when you select one of them. The two "slpkamer" entries are radiators, the "living" and "boiler" ones are the binary relais. For those there is no monitoring involved except the on/off because all other features are greyed out anyway.

![IMG_1C5F75970266-1](https://user-images.githubusercontent.com/65021985/222084994-196af5fb-f61a-4d14-85c9-97ecc6fa084d.jpeg)
![IMG_54A76E15C25D-1](https://user-images.githubusercontent.com/65021985/222085003-cef765c3-2e9a-473d-b8e9-8903141967f2.jpeg)

**Comment by hemphen** [comment]
I have added support for "electrical outlets", but since I don't own any it is a bit experimental. I _think_ they should work, both for reading and writing states, but I can't be certain. Please test and compare to the official app and provide feedback if possible.

**Comment by minosrex** [comment]
Thanks. I installed this version, but no new entities show up for the switches...

**Comment by hemphen** [comment]
Ok. That's a bit surprising. Just to confirm. You did
* Install the v0.2.7 version?
* Restart Home Assistant after the update? (This is always a requirement when updating HACS/custom_components, but also necessary for my integration to pick up new devices)

A test that is possible to perform on your side would be to remove the integration/account and re-add it and see if that changes anything.

If that doesn't help it means that switches might be represented in more than one way, and I likely need more information extracted from accessing the app from a desktop web browser. I'll wait for your input to above questions before looking further into this.

**Comment by minosrex** [comment]
Just to be sure, I redid the whole thing (uninstall integration, delete component, restart, download latest again, copied to custom components, restart, add integration). Still the same thirteen entities (one climate and twelve temperature settings), no switches.

**Comment by hemphen** [comment]
Please send me an email to michael.hemph at gmail.com if you want to pursue this further. I need to instruct you how to provide a file with a bit more detailed data of your setup.

**Comment by hemphen** [comment]
Fixed by #4 and published in release v0.3.0.
