### ISSUE TITLE
Presets are not syncing with app/LCD

### ISSUE THREAD

**Issue by citgot** [hemphen/homeassistant-clevertouch#5]
In HA the integration shows all presets that the Clevertouch app has. However changing to a preset in the integration doesn’t register in the app or the LCD unit so the radiators won’t change the settings. 
Is this expected? I would guess the presets are expected to work?

**Comment by hemphen** [comment]
Definitely expected to work. It is slow to register changes however - and I’m not sure that is avoidable. I made one single test right now and that (still) works for me (changing from Comfort to Eco for a single radiator). I waited for maybe 30s without the app reflecting the change - but it did so when refreshing manually.

Does any changes at all work for you? Like changing temperatures etc.?

**Comment by hemphen** [comment]
I did another (limited) test. The LCD display reflects the change much quicker - which is sort of expected. The app DID reflect the change without any user interaction after some period though (in this case 1-2 minutes).

If it still doesn't work for you I likely need more info in order to help finding the issue.

**Comment by citgot** [comment]
Yeah thanks, I got it working after choosing the mode “off”. Then I could choose any other mode and it would register. 
However, I’m using a climate card in HA and that automatically returns to the comfort mode whatever I choose. It looks right in the Clevertouch app though. So maybe I’ll have to find a better card for my dashboard. 
Thanks for making this integration.
